// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzroviriqntmgzzkursh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cm92aXJpcW50bWd6emt1cnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MDExNzksImV4cCI6MjA3NDM3NzE3OX0.xh7-n7zcE6ve156RQne6t8bzWHofddhnm_XLbDSRZ9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});